### ISSUE TITLE
Add support for firing one-time events when observing

### ISSUE THREAD

**Issue by amirebrahimi** [jupyter-widgets/widget-ts-cookiecutter#102]
I have a frequent pattern that comes up time and again and think it would be helpful to have this supported in the API:
```
append_type_radio.observe(toggle_append_type, names='value');
toggle_append_type({'new': toggle_append_radio.value}) # call it once to initialize
```

^-- the above is a hack and I would much prefer a way to have a signal automatically come when subscribing
or, optionally, a way to manually trigger an event, so that anything that depends on initial state can get updated.

**Comment by ianhi** [comment]
Hi @amirebrahimi I agree that eager execution of a callback for initalization would be a useful feature. However, I think the place to ask for this is over on https://github.com/ipython/traitlets as the `observe` function is inherited from `traitlets.HasTraits` https://traitlets.readthedocs.io/en/stable/api.html#traitlets.HasTraits.observe

Also, in general for feature requests for widgets you probably want the main ipywidgets repo: https://github.com/jupyter-widgets/ipywidgets

So I'm going to close this here but feel free to open a new feature request in those other places (Of the two I'd reocmmend traitlets)
