### ISSUE TITLE
Publishing custom JupyterWidget

### ISSUE THREAD

**Issue by LordHeImchen** [jupyter-widgets/widget-ts-cookiecutter#112]
Hey guys,
I am trying to publish my custom jupyter widget following the steps you provide in the ReadMe.
Unfortunately when executing `twine check dist/*` i receive the following error message:

`Checking dist/UNKNOWN-0.0.0-py2.py3-none-any.whl: InvalidDistribution: Invalid distribution metadata. This version of twine supports Metadata-Version 1.0, 1.1, 1.2, 2.0, 2.1, and 2.2`

To be honest, i don't know how to fix this issue. I looked through my code and couldn't find anything which defines `metadata-version`... Furthermore i don't understand where the file twine is referring to with "UNKNOWN-0.0.0-py2.py3-none-any.whl" is coming from, but it is in my dist folder and i can't read it.

Can anyone help me out?
Thanks in advance!

**Comment by ianhi** [comment]
Hi @LordHeImchen can you give a link to your code to look at? What's being put as UNKNOWN should be determined by this line in setup.py: https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/0e0116cfc12fd61b18d89d17145031992373076b/%7B%7Bcookiecutter.github_project_name%7D%7D/setup.py#L29 so it'

**Comment by ianhi** [comment]
> Furthermore i don't understand where the file twine is referring to with "UNKNOWN-0.0.0-py2.py3-none-any.whl" is coming from, but it is in my dist folder and i can't read it.

This should be generated by the `python -m build` step - wheels (.whl) are basically zip files that pip uses to install packages so it makes sense that you can't read it

**Comment by ianhi** [comment]
also are there any other files in the dist folder? if so what are their names?

**Comment by adpatter** [comment]
I see the following files there when I run `jlpm run build`:
`[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ ls dist
index.js  index.js.map`

**Comment by adpatter** [comment]
The repo that I am working on is here:  https://github.com/educational-technology-collective/etc_jupyterlab_distribution

**Comment by ianhi** [comment]
@adpatter can you try running 

```
pip install build
python -m build
```

**Comment by adpatter** [comment]
```
[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ ls -la dist
total 124
drwxrwxr-x. 1 null null   198 Jan  7 11:51 .
drwxrwxr-x. 1 null null  1016 Jan  7 11:50 ..
-rw-rw-r--. 1 null null 69651 Jan  7 11:50 etc_jupyterlab_distribution-0.1.0.dev0.tar.gz
-rw-rw-r--. 1 null null 12231 Jan  7 11:43 index.js
-rw-rw-r--. 1 null null 33163 Jan  7 11:43 index.js.map
-rw-rw-r--. 1 null null  2975 Jan  7 11:51 UNKNOWN-0.0.0-py2.py3-none-any.whl
```

**Comment by adpatter** [comment]
@ianhi  This is the result of `twine check dist/*`:

```
[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ twine check dist/*
Checking dist/UNKNOWN-0.0.0-py2.py3-none-any.whl: InvalidDistribution: Invalid distribution metadata. This version of twine supports Metadata-Version 1.0, 1.1, 1.2, 2.0, 2.1, and 2.2
```

**Comment by ianhi** [comment]
thanks. Can you post the outputs of the `python -m build` in full? You can make it collapseable with the details block: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d

**Comment by adpatter** [comment]
<details>
[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (jupyter_packaging==0.7.9, jupyterlab==3.*, setuptools>=40.8.0, wheel)
* Getting dependencies for sdist...
/tmp/build-env-fo68wg7n/lib/python3.9/site-packages/setuptools/dist.py:493: UserWarning: Normalizing '0.1.0.dev' to '0.1.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running egg_info
warning: no files found matching '.coverage.rc'
warning: no files found matching 'etc_jupyterlab_distribution/labextension/*.tgz'
warning: no previously-included files found matching 'docs/#*'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
no previously-included directories found matching 'docs/dist'
warning: no directories found matching 'examples'
warning: no directories found matching 'tests'
no previously-included directories found matching 'tests/build'
no previously-included directories found matching '**/node_modules'
no previously-included directories found matching 'coverage'
no previously-included directories found matching 'lib'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
writing manifest file 'etc_jupyterlab_distribution.egg-info/SOURCES.txt'
* Building sdist...
/tmp/build-env-fo68wg7n/lib/python3.9/site-packages/setuptools/dist.py:493: UserWarning: Normalizing '0.1.0.dev' to '0.1.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running sdist
running jsdeps
running handle_files
running check
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too

warning: WrappedCommand: standard file not found: should have one of README, README.txt, README.rst

warning: WrappedCommand: standard file '_in_process.py' not found

running egg_info
warning: no files found matching '.coverage.rc'
warning: no files found matching 'etc_jupyterlab_distribution/labextension/*.tgz'
warning: no previously-included files found matching 'docs/#*'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
no previously-included directories found matching 'docs/dist'
warning: no directories found matching 'examples'
warning: no directories found matching 'tests'
no previously-included directories found matching 'tests/build'
no previously-included directories found matching '**/node_modules'
no previously-included directories found matching 'coverage'
no previously-included directories found matching 'lib'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
writing manifest file 'etc_jupyterlab_distribution.egg-info/SOURCES.txt'
warning: no files found matching '.coverage.rc'
warning: no files found matching 'etc_jupyterlab_distribution/labextension/*.tgz'
warning: no previously-included files found matching 'docs/#*'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
no previously-included directories found matching 'docs/dist'
warning: no directories found matching 'examples'
warning: no directories found matching 'tests'
no previously-included directories found matching 'tests/build'
no previously-included directories found matching '**/node_modules'
no previously-included directories found matching 'coverage'
no previously-included directories found matching 'lib'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
writing manifest file 'MANIFEST'
creating etc_jupyterlab_distribution-0.1.0.dev0
creating etc_jupyterlab_distribution-0.1.0.dev0/css
creating etc_jupyterlab_distribution-0.1.0.dev0/docs
creating etc_jupyterlab_distribution-0.1.0.dev0/docs/source
creating etc_jupyterlab_distribution-0.1.0.dev0/docs/source/_static
creating etc_jupyterlab_distribution-0.1.0.dev0/docs/source/examples
creating etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution
creating etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension
creating etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
creating etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/nbextension
creating etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/tests
creating etc_jupyterlab_distribution-0.1.0.dev0/src
creating etc_jupyterlab_distribution-0.1.0.dev0/src/__tests__
hard linking LICENSE.txt -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking README.md -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking etc_jupyterlab_distribution.json -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking install.json -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking package.json -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking pyproject.toml -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking pytest.ini -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking setup.cfg -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking tsconfig.json -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking webpack.config.js -> etc_jupyterlab_distribution-0.1.0.dev0
hard linking css/widget.css -> etc_jupyterlab_distribution-0.1.0.dev0/css
hard linking docs/Makefile -> etc_jupyterlab_distribution-0.1.0.dev0/docs
hard linking docs/environment.yml -> etc_jupyterlab_distribution-0.1.0.dev0/docs
hard linking docs/make.bat -> etc_jupyterlab_distribution-0.1.0.dev0/docs
hard linking docs/source/conf.py -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source
hard linking docs/source/develop-install.rst -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source
hard linking docs/source/index.rst -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source
hard linking docs/source/installing.rst -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source
hard linking docs/source/introduction.rst -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source
hard linking docs/source/_static/embed-bundle.js -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source/_static
hard linking docs/source/_static/embed-bundle.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source/_static
hard linking docs/source/_static/helper.js -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source/_static
hard linking docs/source/examples/index.rst -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source/examples
hard linking docs/source/examples/introduction.nblink -> etc_jupyterlab_distribution-0.1.0.dev0/docs/source/examples
hard linking etc_jupyterlab_distribution/__init__.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution
hard linking etc_jupyterlab_distribution/_frontend.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution
hard linking etc_jupyterlab_distribution/_version.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution
hard linking etc_jupyterlab_distribution/widget.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution
hard linking etc_jupyterlab_distribution/labextension/build_log.json -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension
hard linking etc_jupyterlab_distribution/labextension/package.json -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension
hard linking etc_jupyterlab_distribution/labextension/static/lib_index_js.f135dec82444fd3e5957.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/lib_index_js.f135dec82444fd3e5957.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/lib_plugin_js.9fcdd0fbfcd9779fdd28.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/lib_plugin_js.9fcdd0fbfcd9779fdd28.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/lib_widget_js.9766f24e56ee53f9c2ce.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/lib_widget_js.9766f24e56ee53f9c2ce.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/node_modules_educational-technology-collective_etc_smartboard_dist_index_js.751eb7fc32a28e79664b.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/node_modules_educational-technology-collective_etc_smartboard_dist_index_js.751eb7fc32a28e79664b.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/remoteEntry.a3401e3fda4d3d396176.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/remoteEntry.a3401e3fda4d3d396176.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/labextension/static/style.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/labextension/static
hard linking etc_jupyterlab_distribution/nbextension/extension.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/nbextension
hard linking etc_jupyterlab_distribution/nbextension/index.js -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/nbextension
hard linking etc_jupyterlab_distribution/nbextension/index.js.map -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/nbextension
hard linking etc_jupyterlab_distribution/tests/__init__.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/tests
hard linking etc_jupyterlab_distribution/tests/conftest.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/tests
hard linking etc_jupyterlab_distribution/tests/test_example.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/tests
hard linking etc_jupyterlab_distribution/tests/test_nbextension_path.py -> etc_jupyterlab_distribution-0.1.0.dev0/etc_jupyterlab_distribution/tests
hard linking src/extension.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src
hard linking src/index.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src
hard linking src/plugin.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src
hard linking src/version.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src
hard linking src/widget.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src
hard linking src/__tests__/index.spec.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src/__tests__
hard linking src/__tests__/utils.ts -> etc_jupyterlab_distribution-0.1.0.dev0/src/__tests__
Creating tar archive
removing 'etc_jupyterlab_distribution-0.1.0.dev0' (and everything under it)
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (jupyter_packaging==0.7.9, jupyterlab==3.*, setuptools>=40.8.0, wheel)
* Getting dependencies for wheel...
running egg_info
creating UNKNOWN.egg-info
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running install
running install_egg_info
running egg_info
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
Copying UNKNOWN.egg-info to build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0-py3.9.egg-info
running install_scripts
Successfully built etc_jupyterlab_distribution-0.1.0.dev0.tar.gz and UNKNOWN-0.0.0-py2.py3-none-any.whl
</details>

**Comment by adpatter** [comment]
@ianhi Please let me know if I can provide any further information.  Thank you.

**Comment by adpatter** [comment]
As an aside, I get get the same result when I remove 'dev' from _version.py.

**Comment by ianhi** [comment]
I can replicate the `UNKNOWN` wheel being generated with a freshly generated project from the cookeicutter so theres definitely a bug that's been introduced somewhere in the chain (or some change that broke this)

**Comment by ianhi** [comment]
I wonder if this has something to do with:

```
warning: check: missing meta-data: if 'author' supplied, 'author_email' should be supplied too

warning: WrappedCommand: standard file not found: should have one of README, README.txt, README.rst

warning: WrappedCommand: standard file '_in_process.py' not found
```

`_in_process.py` is involved in the build backed: https://github.com/pypa/pip/blob/d01dd4aba73799e6fab87e360d61bf0fcc525115/src/pip/_vendor/pep517/in_process/_in_process.py

so it not being found is certainly not great

**Comment by ianhi** [comment]
as a workaround it looks as though doing:

```
python setup.py sdist bdist_wheel
```

(the "old way") still works and avoids the issues with using build backends

**Comment by adpatter** [comment]
```
[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ twine check dist/*
Checking dist/etc_jupyterlab_distribution-0.1.0.dev0-py2.py3-none-any.whl: PASSED
Checking dist/etc_jupyterlab_distribution-0.1.0.dev0.tar.gz: PASSED
Checking dist/index.js: InvalidDistribution: Unknown distribution format: 'index.js'
```

@ianhi Should `index.js` be getting into `dist`?

**Comment by ianhi** [comment]
is that maybe leftover from earlier? can you delete dist and then build the wheel?

**Comment by adpatter** [comment]
Running `jlpm run build` puts `index.js` in `dist`.

**Comment by adpatter** [comment]
I was able to build the wheel using the old method: `python setup.py sdist bdist_wheel`

**Comment by adpatter** [comment]
It is published here: https://pypi.org/project/etc-jupyterlab-distribution/0.1.0/

**Comment by adpatter** [comment]
@ianhi When I delete `dist` and build using the old method, I get the result in `dist`:

```
[~/workspace/educational-technology-collective/etc_jupyterlab_distribution] (etc_jupyterlab_distribution)
$ ls dist
etc_jupyterlab_distribution-0.1.0-py2.py3-none-any.whl  etc_jupyterlab_distribution-0.1.0.tar.gz
```

**Comment by adpatter** [comment]
@ianhi When I install the package with `pip install etc_jupyterlab_distribution` and try to evaluate the widget, it shows:
`Error displaying widget: model not found`

If I build using the old method, is there anything else I need to do in order to get the widget to display?

**Comment by adpatter** [comment]
@ianhi Thank you for all the help.  The widget is working perfectly.  Please let me know if there is anything I can do with regard to helping with the topic of this issue.  I will continue to monitor it.

**Comment by LordHeImchen** [comment]
Hey guys,
in the meantime i was able to work around my issues. You can see how i solved it right [here](https://github.com/pypa/twine/issues/853#issuecomment-1006613812).

As a little conclusion for you guys:
1. First i had the problem that my wheel wasn't building correctly, which could be resolved by manually adding `include setup.py` in `MANIFEST.in`.
2. After that, `twine build dist/*` failed because of the other files in my dist folder. So what i did as a hacky workaround was simply putting both the `.whl` and the `.tar.gz` files into a subfolder and called `twine build dist/subfolder/*` and it worked.

> I can replicate the UNKNOWN wheel being generated with a freshly generated project from the cookeicutter so theres definitely a bug that's been introduced somewhere in the chain (or some change that broke this)

However, as @ianhi already pointed out, some bug is definitely in that chain...
The files should be removed from the `dist` folder and `setup.py` needs to be included into `MANIFEST.in`.

Hope this helps in finding the bug and anyhow thanks for the support with this amazing template!

**Comment by adpatter** [comment]
For clarification, I built the package using the "old method" and removed the .js files from dist and then published the package.  Then I installed the package using pip and I installed ipywidgets using conda, and it worked.
