### ISSUE TITLE
mkdirp doesn't work on Mac by default

### ISSUE THREAD

**Issue by astrofrog** [jupyter-widgets/widget-ts-cookiecutter#16]
After some investigation for https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/15 I realized that my issue was that locally ``mkdirp`` doesn't exist on MacOSX but that error was hidden. I think the use of mkdirp in the following file:

https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/9f378b1885e50d85bfbe677f7398d00bf63f9203/%7B%7Bcookiecutter.github_project_name%7D%7D/package.json

should maybe be changed to just mkdirp since it doesn't seem mkdirp is really needed?

**Comment by vidartf** [comment]
The `mkdirp` command is installed by the [`mkdirp` npm package](https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/9f378b1885e50d85bfbe677f7398d00bf63f9203/%7B%7Bcookiecutter.github_project_name%7D%7D/package.json#L62). Does this package not work on OSX?

**Comment by astrofrog** [comment]
Should it get auto-installed while running e.g. ``python setup.py sdist``?

**Comment by vidartf** [comment]
Yes.

**Comment by vidartf** [comment]
The log you posted in #15 also indicates that it was installed: `├─┬ mkdirp@0.5.1`

**Comment by vidartf** [comment]
Oh, that was from the install from the sdist. Would you mind pasting the log from `python setup.py sdist` ?

**Comment by vidartf** [comment]
@astrofrog I just merged a PR #17 that fixes some problems. Would you mind running your test again of the latest master and see if that solves your problem?

**Comment by vidartf** [comment]
Closed due to lack of feedback. I'll be happy to reopen if someone can supply more details.
