### ISSUE TITLE
Errors building opinionated-widget-cookiecutter

### ISSUE THREAD

**Issue by orpheus92** [jupyter-widgets/widget-ts-cookiecutter#2]
I was trying to build custom widget with this repository. The python part ran without error. I had problem with the ts part. 
Below is the errors I got. 
src/plugin.ts(43,27): error TS2345: Argument of type '{ name: string; version: string; exports: typeof "/media/orpheus92/OS/Anaconda/reg_wid/src/widget...' is not assignable to parameter of type 'IWidgetRegistryData'.
  Types of property 'exports' are incompatible.
    Type 'typeof "/media/orpheus92/OS/Anaconda/reg_wid/src/widget"' is not assignable to type 'ExportData'.
      Type 'typeof "/media/orpheus92/OS/Anaconda/reg_wid/src/widget"' is not assignable to type '() => Promise<ExportMap>'.
        Type 'typeof "/media/orpheus92/OS/Anaconda/reg_wid/src/widget"' provides no match for the signature '(): Promise<ExportMap>'.

Any idea why this is happening?

**Comment by vidartf** [comment]
Could you give a little more detailed breakdown of what you did beforehand?
 - After using the cookiecutter, did you make any changes to the files?
 - What command gave this error?
 - Did you run any other commands before the command that gave the error?

**Comment by orpheus92** [comment]
So after I use the cookiecutter to generate the folder, I tried to do pip install -e .
It gave the error as I showed. 

Then I tried to do install the python first with pip install .  It did not give me any error. 
Then I ran npm install, which did not give errors. 
Then I ran npm run build, which gave the same error as above. 

Not sure what is wrong.

**Comment by vidartf** [comment]
I can recreate it, I'll have a look at it.

**Comment by vidartf** [comment]
There are some refactoring of things between widgets and jupyterlab that is causing this. I'll wait for the dust to settle there before debugging further (cc @blink1073, @jasongrout).

**Comment by jasongrout** [comment]
Thanks for flagging us. Yes, we're currently changing our opinion about how widgets should be designed for jlab.

**Comment by vidartf** [comment]
Should have been fixed by #3, will close once I can confirm.

**Comment by vidartf** [comment]
As far as I can tell, this is now fixed. Feel free to reopen if you are still having issues.
