### ISSUE TITLE
Displaying example widget in Jupyter lab

### ISSUE THREAD

**Issue by annazhelt** [jupyter-widgets/widget-ts-cookiecutter#20]
I have followed all the steps in the README up to `npm test`. All the steps executed successfully. 
I would like to display the widget in Jupyter lab so I have also run 
```
pip install ipywidgetexample
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
However, when I try to run `jupyter lab` and display the example widget I get the following errors:

![screen shot 2018-05-10 at 9 17 03 am](https://user-images.githubusercontent.com/12523017/39880546-f7d96cce-5432-11e8-82b5-1d29f70b5a1a.png)

The following is my output after I run `jupyter labextension list`:
```
JupyterLab v0.32.1
Known labextensions:
   app dir: /anaconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
```

Am I missing some steps in getting the widget to work in Jupyter lab? Do I have to release the package to be able to display the widget in Jupyter lab?

Thank you very much for your help!

**Comment by vidartf** [comment]
I guess the outer README could need some more details. After the `pip install -e ".[test, examples]"` command, you will need to register your extensions with notebook/lab. For lab this is done by

```
jupyter labextension install <local path to repo>
```

You will only have to do this step when you are developing your extension. `pip install <extension name>` will only work after you have released/packaged your package, but that command will try to automatically register your extensions.

**Comment by vidartf** [comment]
I've updated the README in https://github.com/jupyter-widgets/widget-ts-cookiecutter/commit/725366c839d6540d4b3f61b2547211edd7d874b8.

**Comment by annazhelt** [comment]
Thank you, that worked! 

I had tried to run that command before, but the command would always hang. I looked more into it, and downgrading from Node 10 to Node 8 solved the issue.
