### ISSUE TITLE
installing from tar or egg.

### ISSUE THREAD

**Issue by eric-kimbrel** [jupyter-widgets/widget-ts-cookiecutter#25]
Hello, thanks for this great cookiecutter template.  It was a huge help getting me started.  I am having issues getting an nbextension  (or labs extension) installed from a zip or egg file.  

I have a couple of packages that i don't want to publish but i do want to be able to install on a few different environments.  Do you have any advice for packaging and installing without publishing the source?

**Comment by vidartf** [comment]
Ideally, you should be able to distribute this as an sdist, or at the very least as a wheel. I have very little experience with eggs, so I don't think I can help you much there. What are the issues you are having?

**Comment by vidartf** [comment]
@eric-kimbrel Are you still having issues? If so, could you share some more details? If not, how did you resolve them?

**Comment by vidartf** [comment]
Alright, closing for now. If anyone is able to supply more details on this issue, I'd be happy to reopen it in the future.
