### ISSUE TITLE
Add config for readthedocs?

### ISSUE THREAD

**Issue by frankier** [jupyter-widgets/widget-ts-cookiecutter#28]
Would it be worth adding config for readthedocs? Here's how I did it for my widget library.

First I made readthedocs use conda so I could install a newer version of npm than is available otherwise. See: https://github.com/industrial-optimization-group/desdeo-vis/blob/master/readthedocs.yml and https://github.com/industrial-optimization-group/desdeo-vis/blob/master/docs/environment.yml

Then I added widget building to the setup() function in conf.py https://github.com/industrial-optimization-group/desdeo-vis/blob/7b1b7611f2d3a19d4d8ed18a28785fc79bfbbcb1/docs/conf.py#L225

**Comment by vidartf** [comment]
There is already a docs + readthedocs.yml in the repo (https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/readthedocs.yml). For specific changes, feel free to open one or more PRs!

**Comment by vidartf** [comment]
Closing due to lack of feedback. I'll be happy to reopen if there are any further points to consider!
