### ISSUE TITLE
custom widget working locally but not with NBViewer or as HTML file with embedded widget

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/widget-ts-cookiecutter#29]
During the JupyterCon community sprint day @jasongrout helped me re-build my widget using the new widget-ts-cookiecutter. I'm able to get the widget (https://github.com/ismms-himc/clustergrammer_widget2) running locally in a notebook but it is not being rendered within a static HTML file or in NBViewer (I saved the notebook with the widget state). 

Here is the NBViewer link: http://nbviewer.jupyter.org/github/ismms-himc/clustergrammer_widget2/blob/master/examples/introduction.ipynb

```
clustergrammer_widget2.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
23embed-amd.js:293176 

Falling back to unpkg.com for clustergrammer_widget2@1.0.0
index.js:1 

Failed to load resource: the server responded with a status of 404 ()
introduction.ipynb:1 Refused to execute script from 'https://unpkg.com/clustergrammer_widget2@1.0.0/dist/index.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
23embed-amd.js:40870 Could not instantiate widget
(anonymous) @ embed-amd.js:40870
24require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165 Uncaught (in promise) Error: Script error for "clustergrammer_widget2"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:165)
    at HTMLScriptElement.onScriptError (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1732)
```

It looks like it is looking for version `1.0.0` of clustergrammer_widget2. Do I need to set the version of this as well (if so there was no mention of this in the README instructions for publishing). Any help would be greatly appreciated.

**Comment by jasongrout** [comment]
Looking at the cookie cutter, the widget-ts-cookiecutter should have another section in the webpack, like this: https://github.com/jupyter-widgets/widget-cookiecutter/blob/0aa620eaa2b4365ccfc755eb2a9262e2f6bed974/%7B%7Bcookiecutter.github_project_name%7D%7D/js/webpack.config.js#L45-L71
Also, the cookiecutter should have a files entry in the package.json like this: https://github.com/jupyter-widgets/widget-cookiecutter/blob/0aa620eaa2b4365ccfc755eb2a9262e2f6bed974/%7B%7Bcookiecutter.github_project_name%7D%7D/js/package.json#L18-L21

**Comment by cornhundred** [comment]
I tried setting the `webpack.config` embed section entry to [`lib/widget.js`](https://github.com/ismms-himc/clustergrammer_widget2/blob/working/webpack.config.js#L65). But, NBViewer is still [failing](http://nbviewer.jupyter.org/github/ismms-himc/clustergrammer_widget2/blob/working/examples/introduction.ipynb) and it seems to be because unpkg does not have the distribution

The console is giving a 404 error for the URL https://unpkg.com/clustergrammer_widget2@0.4.3/dist/index.js

**Comment by cornhundred** [comment]
I noticed that I get a 404 error for `dist`

https://unpkg.com/clustergrammer_widget2@0.4.3/dist/index.js

but the file is found for `lib`

https://unpkg.com/clustergrammer_widget2@0.4.3/lib/index.js

I will try out changing the `publicPath` in the [`webpack.config`](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/webpack.config.js#L71)

**Comment by cornhundred** [comment]
I got the widget embedding working on NBViewer ([link](http://nbviewer.jupyter.org/github/ismms-himc/clustergrammer_widget2/blob/master/examples/introduction.ipynb)) by fixing the [webpack.config](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/webpack.config.js#L66) (I tried to make it similar to the webpack.config from the non TypeScript cookie-cutter). But I'm still getting an error when I try to view the widget in a static HTML file ([link](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/examples/html_notebooks/introduction.html)).

<img width="1044" alt="screen shot 2018-09-03 at 4 33 04 pm" src="https://user-images.githubusercontent.com/8352840/45000980-2fb34380-af97-11e8-8fda-deca8c51fcbc.png">

The error might be due to it looking for `jupyter-widgets/base` `dist` instead of the `lib`.

**Comment by cornhundred** [comment]
The "Embed Widgets" option works ([link](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/examples/html_notebooks/embed_widget.html)) and I'm able to see the widget render. So I'll try and find out what the static HTML file is doing differently than the embedded HTML. I see that my [Introduction.html](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/examples/html_notebooks/introduction.html#L4) is referencing `jupyter-js-widgets` which is no longer used from what I can gather from the documentation.

**Comment by cornhundred** [comment]
It looks like the issue I was having with embedding the widget into a static HTML was addressed in nbconvert [here](https://github.com/jupyter/nbconvert/issues/636) and solved with a recent [pull request](https://github.com/jupyter/nbconvert/pull/792). I cloned and pip installed the nbconvert repo and was able to generate an HTML file ([link](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/examples/html_notebooks/introduction2_nbconvert.html)) with a working embedded widget using nbconvert from the command line but not from Jupyter notebook. 

So the original two issues I raised appear to have been fixed:
* Widget embedding in NBViewer was fixed by modifying the [webpack.config](https://github.com/ismms-himc/clustergrammer_widget2/blob/master/webpack.config.js#L52) and 
* Widget embedding in static HTML files was fixed by using the latest un-released [nbconvert](https://github.com/jupyter/nbconvert) from the command line to generate a static HTML file with embedded widgets. 

It would still be great to be able to save static HTML files with embedded widgets using Jupyter notebook or Jupyter Lab ([raised issue here](https://github.com/jupyterlab/jupyterlab/issues/5235)), but using nbconvert from the command line will work for now. Also, I still have to get my custom widget, ([Clustergrammer_Widget2](https://github.com/ismms-himc/clustergrammer_widget2)), working in Jupyter Lab again, but I'll raise this as a separate issue. 

Thanks for setting up the cookie-cutter! It's a really great resource and it's great to be able to render widgets in mybinder ([link](https://mybinder.org/v2/gh/ismms-himc/clustergrammer_widget2/master?filepath=examples%2Fintroduction.ipynb)).

**Comment by cornhundred** [comment]
FYI, I was able to get the widget running in Jupyter lab again by re-running the command `python setup.py sdist bdist_wheel` as described in the [readme](https://github.com/jupyter-widgets/widget-ts-cookiecutter)
