### ISSUE TITLE
Example for running ExampleView

### ISSUE THREAD

**Issue by tlimpanont** [jupyter-widgets/widget-ts-cookiecutter#43]
I expect 'ExampleView' code to be rendered after I executed this code:

![image](https://user-images.githubusercontent.com/617876/51213298-0201e200-191b-11e9-939e-596dde308b04.png)

```
export
class ExampleView extends DOMWidgetView {
  render() {
    this.value_changed();
    this.model.on('change:value', this.value_changed, this);
  }

  value_changed() {
    this.el.textContent = this.model.get('value');
  }
}

```

Can you help me  how to render a simple hello world in jupyter lab within the widget.ts file?

`this.el.textContent` suppose to render in the DOM whatever value is set right?

**Comment by jasongrout** [comment]
You didn't actually display the widget. Try making one more cell with content `w` or `display(w)`.

**Comment by tlimpanont** [comment]
@jasongrout WOW I totally missed the display method. It works by the way. But can you recommend me resources where I can find things about render / display TS related scripts?

**Comment by vidartf** [comment]
Closing as the original issue seems answered.
