### ISSUE TITLE
Building extension.js

### ISSUE THREAD

**Issue by zerline** [jupyter-widgets/widget-ts-cookiecutter#52]
Hi
This cookiecutter is really great, but full of magics!
Reading `webpack.conf.js`, I see `extension.ts` as input and `index.js` as output. Therefore no `extension.js`.
Could somebody explain me how `extension.js` gets built?

**Comment by vidartf** [comment]
extension.js is not built, but is already in place here: https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/%7B%7Bcookiecutter.python_package_name%7D%7D/nbextension/static/extension.js

This maps the output from webpack (index) to the module name when loaded as classic notebook extension.

**Comment by zerline** [comment]
oh yeah .. thx @vidartf
