### ISSUE TITLE
Python packages with dash in the name gets generated

### ISSUE THREAD

**Issue by frankgerhardt** [jupyter-widgets/widget-ts-cookiecutter#54]
The name of my widget is `my-widget`. 

For the Python code I got a package name genrated with that dash in it and nothing worked. That's not legal Python syntax. I'm so sad.

**Comment by vidartf** [comment]
Thanks for sharing your pain. Any suggestions for how to resolve this? 😃

**Comment by frankgerhardt** [comment]
I use `mywidget` as name.

**Comment by vidartf** [comment]
Should this issue be closed then, or is there anything you would want to be changed with the cookiecutter?

**Comment by frankgerhardt** [comment]
The cookiecutter should generate names with `-` for Javascript and with `_` for Python. 
Or at least print an error if a `-` is used and not supported.

**Comment by vidartf** [comment]
This should be possible by using some Jinja2 template logic / filters. Jinja2 is the templating engine that cookiecutter uses. If anyone wants to take a look at this, that would be very welcome. Until then, these rules will have to be followed manually by the user.
