### ISSUE TITLE
Issue with the newest Jupyterlab 2.0.0

### ISSUE THREAD

**Issue by dou-du** [jupyter-widgets/widget-ts-cookiecutter#59]
This cookiecutter seems not working with the newest JupyterLab 2.0.0. For instance, the JupyterLab has changed the library @phosphor/widgets to @lumino/widgets. I try to fix these problems. However, it is still not working. Could you upgrade it to fit with the newest JupyterLab ? Thanks.

**Comment by TermeHansen** [comment]
any news on this issue?
I have also upgraded jupyterlab to 2.0.x, but have problem to get my widget to work.

How do you debug those package name change fails? All I see is:

> semver range ^0.1.0 is not registered as a widget module

**Comment by jasongrout** [comment]
See #60 for the changes needed.

**Comment by TermeHansen** [comment]
Great, thanks!  Now my widget also works in JL 2.0...

**Comment by dou-du** [comment]
Thanks a lot. It is working now for JupyterLab 2.0.
