### ISSUE TITLE
Allow for extra webpack bundles

### ISSUE THREAD

**Issue by blink1073** [jupyter-widgets/widget-ts-cookiecutter#6]
Add handling of lazily loaded webpack bundles.
This requires defining a separate entry point for the notebook extension and adding public webpack config.  Example: https://github.com/matplotlib/jupyter-matplotlib/blob/0f1e870c1ee3583767759fa1134fff429767ac6a/js/src/nb_index.js#L8

**Comment by vidartf** [comment]
Fixed in #19!
