### ISSUE TITLE
Adding a LICENSE file at the root level

### ISSUE THREAD

**Issue by nanchenchen** [jupyter-widgets/widget-ts-cookiecutter#61]
Hello,

I am an engineer at Google interested in using your project. If you are comfortable with permitting this, could you please add an open source license (https://opensource.org/licenses) to your project directory? (Not just inside the {{}} project).

Thank you!

**Comment by jasongrout** [comment]
+1 from me, though perhaps for things like this (where we are generating a set of files that are expressly supposed to be modified), a more permissive license is called for?

**Comment by jasongrout** [comment]
CC @vidartf @blink1073 @cornhundred @jtpio @martinRenou @astrofrog @maartenbreddels @JoaoFelipe (who are listed as contributors) for their thoughts.

**Comment by jasongrout** [comment]
Is a BSD license sufficient for your needs, @nanchenchen?

**Comment by nanchenchen** [comment]
Yes! That works perfectly.

**Comment by maartenbreddels** [comment]
Sounds like a good idea, +1 from me

(from mobile phone)

**Comment by nanchenchen** [comment]
Thank you :)! Can anyone help me add one LICENSE file to the root level of this repo? 
Really appreciate your help :D

**Comment by vidartf** [comment]
BSD-3 will work for me, but TBH it could probably be CC-0 :)

**Comment by jasongrout** [comment]
ping @vidartf @blink1073 @cornhundred @jtpio @martinRenou @astrofrog @JoaoFelipe again for comments on adding a license file for clarification.

**Comment by jtpio** [comment]
BSD-3 sounds good to me too.

**Comment by blink1073** [comment]
👍 for BSD-3

**Comment by martinRenou** [comment]
:+1:

**Comment by nanchenchen** [comment]
Hello! Just wanted to follow up and see if there is anything I need to do on my side. Thanks for your help. :)

**Comment by jasongrout** [comment]
Thanks for following up. I put in a PR, and someone else should merge it. @vidartf?

**Comment by nanchenchen** [comment]
Thank you so much! Super appreciate all your help :)!!!

**Comment by cornhundred** [comment]
Hi, I have a question about the license. We made a widget using this cookiecutter (https://github.com/ismms-himc/clustergrammer2) and are using this BSD 3-clause license from this repo. However, would the licensing rules allow us to to modify the license of our widget made using this cookiecutter (e.g. to MIT to be consistent with our other projects under the Clustergrammer umbrella) or is the widget made using this cookiecutter meant to remain under this license?

**Comment by jasongrout** [comment]
I think it makes sense to have cookiecutters like this to not have any license on the generated output, e.g., CC0 public domain.

**Comment by jasongrout** [comment]
(which is what I was getting at in my [comment above](https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/61#issuecomment-598425757)

**Comment by cornhundred** [comment]
Hi authors, @jasongrout @blink1073 @jtpio @martinRenou @astrofrog @JoaoFelipe (hope I'm not missing anyone) - would you all be alright if we changed the license of a widget that was built using this cookiecutter to MIT (https://github.com/ismms-himc/clustergrammer2)? I tend to agree with @jasongrout about the outputs of the cookiecutter not having a license. Thanks for making a great cookiecutter!

**Comment by jasongrout** [comment]
For the record, I'm okay with the output of this cookie cutter having MIT or even CC0 license.

**Comment by cornhundred** [comment]
Thanks @jasongrout, we plan on transitioning to an MIT license for our widget produced from this cookiecutter. Please let us know if there are any concerns or objections from the other authors of the cookiecutter.

**Comment by hbredin** [comment]
I am currently working on [an audio annotation widget](https://twitter.com/hbredin/status/1588590580590080000?s=20&t=Xs0NyZW_6L4j-K3ZNPrDTA) based on this cookiecutter (which was VERY useful by the way :pray:).

@cornhundred's last message mentioned a possible transition to MIT license.
What is the status on this? IMHO, CC-0 would be even better for this kind of project -- I'd be happy to contribute the transition.
