### ISSUE TITLE
Failed npm test

### ISSUE THREAD

**Issue by gutama** [jupyter-widgets/widget-ts-cookiecutter#64]
Hi,

I made a new project

pip install -e ".[test, examples]"    --> ok
py.test   --> ok

I change the KernelMessage.ICommMsg into ICommMsgMsg in utils spec.ts 

    _process_msg(msg: services.KernelMessage.ICommMsgMsg) {
        if (this._on_msg) {
            return this._on_msg(msg);

but npm test still failed

(base) D:\repogit\myproj\gajupy>npm test

> gajupy@0.1.0 test D:\repogit\myproj\gajupy
> npm run test:firefox

> gajupy@0.1.0 test:firefox D:\repogit\myproj\gajupy
> karma start --browsers=Firefox tests/karma.conf.js

START:
24 04 2020 13:20:25.824:INFO [compiler.karma-typescript]: Compiling project usin
g Typescript 3.1.6
24 04 2020 13:20:29.277:INFO [compiler.karma-typescript]: Compiled 7 files in 34
22 ms.
24 04 2020 13:20:30.500:ERROR [source-reader.karma-typescript]: Error parsing co
de: Unexpected token (30:10)
in D:\repogit\myproj\gajupy\node_modules\@jupyterlab\services\lib\setting\index.
js
at line 30, column 10:

... fetch(id) {
        const { serverSettings } = thi ...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gajupy@0.1.0 test:firefox: `karma start --browsers=Firefox tests/karma.
conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gajupy@0.1.0 test:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ginanjar_utama\AppData\Roaming\npm-cache\_logs\2020-04-24T
06_20_30_560Z-debug.log
npm ERR! Test failed.  See above for more details.

(base) D:\repogit\myproj\gajupy>

here is my screenshot

![image](https://user-images.githubusercontent.com/1462448/80181805-bebf1480-862f-11ea-9657-aa2a4a470763.png)

is there any pointers too look, thanks

ginanjar

**Comment by gutama** [comment]
is something in the configurations not ok? 

below is the log file:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:firefox'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'pretest:firefox', 'test:firefox', 'posttest:firefox' ]
5 info lifecycle gajupy@0.1.0~pretest:firefox: gajupy@0.1.0
6 info lifecycle gajupy@0.1.0~test:firefox: gajupy@0.1.0
7 verbose lifecycle gajupy@0.1.0~test:firefox: unsafe-perm in lifecycle true
8 verbose lifecycle gajupy@0.1.0~test:firefox: PATH: D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\repogit\myproj\gajupy\node_modules\.bin;D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\repogit\myproj\gajupy\node_modules\.bin;d:\Anaconda3;d:\Anaconda3\Library\mingw-w64\bin;d:\Anaconda3\Library\usr\bin;d:\Anaconda3\Library\bin;d:\Anaconda3\Scripts;d:\Anaconda3\bin;d:\Anaconda3\condabin;C:\Python38\Scripts;C:\Python38;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Raytrix Shared\Bin;C:\Windows\System32\Raytrix;C:\Program Files (x86)\Common Files\Raytrix Shared\Bin;D:\Rtools\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;d:\MATLAB\R2018a\bin;C:\Program Files\MATLAB\R2016a\runtime\win64;C:\Program Files\MATLAB\R2016a\bin;C:\Program Files\MATLAB\R2016a\polyspace\bin;d:\MiKTeX2.9\miktex\bin\x64;C:\Program Files (x86)\Smart Projects\IsoBuster;d:\Git\cmd;d:\Python27;d:\Python27\Scripts;C:\Program Files (x86)\HP\Common\HPDestPlgIn;C:\Program Files (x86)\SafeCom\SafeComPrintClient;C:\Program Files\TortoiseGit\bin;d:\ffmpeg\bin;D:\nodejs;C:\ProgramData\chocolatey\bin;.;C:\Users\ginanjar_utama\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\HP\Common\HPDestPlgIn;d:\Java\bin;C:\Users\ginanjar_utama\AppData\Roaming\npm
9 verbose lifecycle gajupy@0.1.0~test:firefox: CWD: D:\repogit\myproj\gajupy
10 silly lifecycle gajupy@0.1.0~test:firefox: Args: [ '/d /s /c', 'karma start --browsers=Firefox tests/karma.conf.js' ]
11 silly lifecycle gajupy@0.1.0~test:firefox: Returned: code: 1  signal: null
12 info lifecycle gajupy@0.1.0~test:firefox: Failed to exec test:firefox script
13 verbose stack Error: gajupy@0.1.0 test:firefox: `karma start --browsers=Firefox tests/karma.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid gajupy@0.1.0
15 verbose cwd D:\repogit\myproj\gajupy
16 verbose Windows_NT 6.3.9600
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:firefox"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error gajupy@0.1.0 test:firefox: `karma start --browsers=Firefox tests/karma.conf.js`
22 error Exit status 1
23 error Failed at the gajupy@0.1.0 test:firefox script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by martinRenou** [comment]
Fixed
