### ISSUE TITLE
Not sure how to run Python tests

### ISSUE THREAD

**Issue by wlievens** [jupyter-widgets/widget-ts-cookiecutter#65]
I tried the following on a newly generated project:

```
pip install -e ".[test, examples]"
py.test
```

But got this error:
```
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --nbval --current-env
```

I'm fairly new to the wider Python ecosystem so I may just not understand how pytest or whatever is used here is supposed to work?

**Comment by martinRenou** [comment]
pytest needs a test file or a directory containing tests as argument.

```
pytest test.py
# or
pytest tests/*
```

**Comment by wlievens** [comment]
The `/tests` directory that the cookiecutter generates is for the frontend (typescript) tests. There is a tests directory in the python module subdirectory though, but if I have to supply that, why is it not documented in the readme?

**Comment by wlievens** [comment]
When I run `py.test gp_widgets/tests` (my project & module name is **gp_widgets**) I get the following error:
```
ImportError while loading conftest '<snip>\gp_widgets\gp_widgets\tests\conftest.py'.
gp_widgets\__init__.py:8: in <module>
    from .widget import GpImageViewerWidget
gp_widgets\widget.py:10: in <module>
    from ipywidgets import DOMWidget
E   ModuleNotFoundError: No module named 'ipywidgets'
```
This is despite ipywidgets being installed globally (with pip) and the widget working fine in Jupyter Lab.

**Comment by martinRenou** [comment]
Please make sure the environment where your pytest is installed contained ipywidgets.

**Comment by martinRenou** [comment]
Closing as it is not an issue concerning the cookiecutter itself

**Comment by wlievens** [comment]
I understand you closing the issue as it's not related to the cookiecutter, but can at least the README.md be adapted to show correct instructions for running the tests?

**Comment by martinRenou** [comment]
Which pytest version do you have? I actually don't see it failing when running `py.test` only. It runs the tests it founds, or it says it did not find tests, but it does not fail.

**Comment by wlievens** [comment]
It seems to work for me too now, apparently "py" and "python" refer to different installations/environments for me. Like I said, I'm fairly new to the ecosystem (less than year) and I find everything about Python (except the language itself) to be incredibly frustrating.

**Comment by wlievens** [comment]
Sorry to keep disturbing you, but another mildly related issue: it seems like pytest also runs the examples notebooks somehow? Is that part of the test strategy as a sort of integration test? My test fails because the reference and test output don't match, am I supposed to write the output of the notebook somewhere as test reference?

**Comment by martinRenou** [comment]
> apparently "py" and "python" refer to different installations/environments for me

I suspect this is a similar reason for not having ipywidgets installed when running the tests.
I would highly recommend using `conda` or other ways to create virtual environments. And I would recommend **never** installing anything on the user location, so never use the Python that is installed by default on your system. If you follow those rules correctly the frustration should disappear.

**Comment by martinRenou** [comment]
> it seems like pytest also runs the examples notebooks somehow

This is disturbing. I would not expect pytest to run a Notebook without having installed a pytest plugin for that.

**Comment by wlievens** [comment]
For other projects I use **pipenv** to manage dependencies and that works reasonably well, though it brings its own share of frustrations compared to a more mature solution like Maven in the Java ecosystem. I haven't dared integrate pipenv into this widget project just yet, one problem at a time :-)

Right now I don't mind "polluting" my user environment with a few global installs since eventually this will have to be built correctly on the CI server we've set up anyway, which should do it in a clean uniform manner.

The notebooks are run when I execute `python -m pytest` at the top level.
```
gp_widgets\tests\test_nbextension_path.py .                                                                      [ 14%]
gp_widgets\tests\test_widget.py ...                                                                              [ 57%]
examples\introduction.ipynb .F.                                                                                  [100%]
```

I definitely don't recall explicitly setting that up. If it works sensibly then I may retain this as some kind of sanity-check integration test, or I'll find a way to exclude it.

**Comment by martinRenou** [comment]
> The notebooks are run when I execute python -m pytest at the top level

I don't know what that happens... I'd check if pytest-notebook is installed https://pypi.org/project/pytest-notebook. Or I would just ignore this issue and explicitly run `pytest gp_widgets\tests\*`.

> I don't have any experience with conda, when I tried it a while back I had a lot of issues getting it to work on Windows

Let me suggest looking at Miniconda https://docs.conda.io/en/latest/miniconda.html which makes a very simple conda installation, without anaconda. I wouldn't know how to make it work on Windows myself, I only suspect it should not be too difficult for someone who knows Windows.

**Comment by wlievens** [comment]
I'm not necessarily interested in having a bundled environment, all I care about is reproducible builds which are pinned to precise versions. That's why I use Pipenv, it comes with a locking system and virtual environment model. In my view it's a very poor solution compared to how mature ecosystems handle it but at least it covers the basic principles.

**Comment by wlievens** [comment]
BTW I found why the notebooks were getting executed: the cookiecutter includes the **nbval** library which does exactly that.

https://pypi.org/project/nbval/

**Comment by martinRenou** [comment]
Thanks for getting back with the reason why it happens. Do you think the Notebook should actually be fixed on the repo then? You said one Notebook is failing?

**Comment by wlievens** [comment]
The notebook I made was failing this test. I haven't figured out why yet. Whether or not notebooks should be part of this notebook is up to you, I don't have a string opinion either way. It could work as a test case.

**Comment by martinRenou** [comment]
Use `conda`, it uses a solver to solve the environment and tries to find a suitable versions combination ;)

If it does not find a suitable solution, it will tell you.

**Comment by wlievens** [comment]
But how does conda do reproducible builds?

**Comment by martinRenou** [comment]
Maybe look at this: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments It might be what you want

**Comment by wlievens** [comment]
Thanks, maybe it is and maybe I can ditch the shitty pipenv system if this is better.
