### ISSUE TITLE
plugin does not activate in jupyterlab 2

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/widget-ts-cookiecutter#68]
Following the installation instructions results in the example widget not rendering on jupyterlab 2.1.2
(I'm using 2.1.2 because jupyter lab --watch is broken on 2.1.3)

## Steps to reproduce
1. Install
```bash
conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab=2.1.2 nodejs
conda activate jlab-test
pip install cookiecutter
cookiecutter https://github.com/jupyter-widgets/widget-ts-cookiecutter.git
cd widget_test
pip install -e ".[test, examples]"
jupyter labextension install .
jupyter lab
```
2. open examples > Introduction.ipynb
3. Add a cell to output `w`
4. run all cells
See errors in browser console + widget does not render:

![image](https://user-images.githubusercontent.com/10111092/83341093-670a6d80-a2ad-11ea-854a-7ca8201ac59e.png)

![image](https://user-images.githubusercontent.com/10111092/83341107-93be8500-a2ad-11ea-9b0f-c5d78a1345a5.png)

### Jupyter lab-manager required?

I think every widget I've ever installed require me to install `jupyterlab-manager` prior to installing the widget. Is this required?

**Comment by vidartf** [comment]
> Is this required?

Yes, the widget manager is required (`jupyter labextension install @jupyter-widgets/jupyterlab-manager`). If you have any suggestions for additions to the readme / comments that would make this apparent, a PR would be very welcome!

**Comment by ianhi** [comment]
Is there any chance of jupyterlab-manager being included by default in jupyterlab? Alternatively is there anything preventing inclusion of the `upyterlab-manager` as a dependency in package.json?

**Comment by ianhi** [comment]
> a PR would be very welcome!

:+1: Until I get to that below is all the changes I had to make in case any googlers end up here:

I had to make two additional changes beyond installing jupyterlab-manager
**1.** 
```diff
diff --git a/package.json b/package.json
index 01e33da..f83c56f 100644
--- a/package.json
+++ b/package.json
@@ -49,7 +49,7 @@
     "watch:nbextension": "webpack --watch"
   },
   "dependencies": {
-    "@jupyter-widgets/base": "^1.1.10 || ^2"
+    "@jupyter-widgets/base": "^1.1.10 || ^2 || ^3"
   },
   "devDependencies": {
     "@phosphor/application": "^1.6.0",
```

**2.**
```diff
diff --git a/src/plugin.ts b/src/plugin.ts
index e88f7db..fc51a6c 100644
--- a/src/plugin.ts
+++ b/src/plugin.ts
@@ -26,7 +26,7 @@ const EXTENSION_ID = 'widget_test:plugin';
  */
 const examplePlugin: IPlugin<Application<Widget>, void> = {
   id: EXTENSION_ID,
-  requires: [IJupyterWidgetRegistry],
+  requires: [IJupyterWidgetRegistry as any],
   activate: activateWidgetExtension,
   autoStart: true
 };
```
with those changes these commands should work:
```bash
conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab nodejs
conda activate jlab-test
pip install cookiecutter
cookiecutter https://github.com/jupyter-widgets/widget-ts-cookiecutter.git
cd widget_test
jupyter labextension install @jupyter-widgets/jupyterlab-manager
pip install -e ".[test, examples]"
jupyter labextension install .
jupyter lab
```

**Comment by ianhi** [comment]
Also this PR: https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/60 seems to solve the extra issues I ran into
