### ISSUE TITLE
README clarification for development

### ISSUE THREAD

**Issue by cabreraalex** [jupyter-widgets/widget-ts-cookiecutter#73]
I'm just getting started playing around with a widget, but am unsure what I need to run as I iterate.

Do I simply run `pip install` every time I make changes? Could there be a section in the README suggesting the best dev process?

**Comment by martinRenou** [comment]
If you do `pip install -e .` (`-e` means editable) then you only need to re-import the Python package in the Notebook to fetch the latest development version, no need to reinstall it manually.

**Comment by ianhi** [comment]
See also https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/72

**Comment by cabreraalex** [comment]
Awesome, #72 was just what I was looking for, thanks!

**Comment by martinRenou** [comment]
Thanks a lot @ianhi
