### ISSUE TITLE
remove pushd and popd from travis

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/widget-ts-cookiecutter#81]
In https://github.com/QuantStack/ipycytoscape/pull/124 (relevant [commit](https://github.com/QuantStack/ipycytoscape/pull/124/commits/0c2370a40f71f535f660793421a337b96c40291d)) I found that these lines https://github.com/jupyter-widgets/widget-ts-cookiecutter/blob/0e4a4cdbcdebe713b2b9a24b80ec601453c56df5/%7B%7Bcookiecutter.github_project_name%7D%7D/.travis.yml#L58-L60
prevented the nbval tests from running the examples. Changing it to:

```
       pytest -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov={{ cookiecutter.python_package_name }} || EXIT_STATUS=$? 
```

got the nbval tests to run again. Though I'm not sure if this was the correct approach because I don't know what the consequences of removing `pushd` and `popd` are.

If this was a reasonable change I can make a PR changing the cookiecutter.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/91 which removed Travis
