### ISSUE TITLE
Upgrade the packages in template 

### ISSUE THREAD

**Issue by anant-k-singh** [jupyter-widgets/widget-ts-cookiecutter#87]
It would be great if this template could use the latest version of all npm packages, specially the new **@jupyter-widgets/base v4**

**Comment by jtpio** [comment]
Thanks @anant-k-singh.

I think this will be fixed by https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/83.

**Comment by jasongrout** [comment]
Yes, let's consolidate discussion over there.
