### ISSUE TITLE
Example not working in Jupyter lab

### ISSUE THREAD

**Issue by willeppy** [jupyter-widgets/widget-ts-cookiecutter#89]
I cannot get the default code to run in Jupyter lab. However it shows up just fine in Jupyter notebook.

### Description

I copied the cookie cutter to my local machine and then ran the below to install:

```bash
pip install -e .
jlpm build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install .
```

I made no changes to the source files. However the example does not work in Jupyter lab for me

<img width="748" alt="nb" src="https://user-images.githubusercontent.com/13400543/106698808-8cbfe300-65af-11eb-9077-c2c900833b38.png">

My JS console in browser has the following errors about model not found:

<img width="1414" alt="Screen Shot 2021-02-02 at 11 36 44 PM" src="https://user-images.githubusercontent.com/13400543/106698838-a06b4980-65af-11eb-87f5-74426dbd63b5.png">

Did I set it up wrong somehow or is this an issue with the cookie cutter? Thanks for the help!

### OS
- Mac OS Big Sur 11.1
- Python 3.9.1
- Jupyter lab 3.0.7
- Jupyter notebook 6.2.0

**Comment by jasongrout** [comment]
This has not yet been updated for JupyterLab 3. That discussion and PR is over in #83

**Comment by willeppy** [comment]
Ah didn't realize that wasn't merged in yet. Working great with jl2. Thanks!

**Comment by Crushellini** [comment]
I've been experiencing this issue as well. Have there been any updates?
